name: Build WASM from C

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          echo "EMSDK_PATH=$(pwd)" >> $GITHUB_ENV
          echo "$EMSDK_PATH" >> $GITHUB_PATH

      - name: Compile C to WASM
        run: |
          emcc your_c_file.c -o your_output_name.html -s WASM=1 -s EXPORTED_FUNCTIONS="['_your_c_function_name']" -s EXPORT_ES6=1 -s MODULARIZE=1
        working-directory: ./your_source_code_directory # Adjust if your C file is in a subdirectory

      - name: Upload WASM and JS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-build
          path: |
            st7789-chip.wasm
            st7789-chip.js
