name: Build WASM from C

on:
  push:
    branches:
      - main

jobs:
  build-wasm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: "emsdk"
      uses: mymindstorm/setup-emsdk@v14
      
    - name: Compile C to WebAssembly
      run: |
        emcc st7789.chip.c -o st7789-chip.wasm --no-entry -s WASM=1 -O3

    - name: Upload WebAssembly artifact
      uses: actions/upload-artifact@v4
      with:
        name: wasm-build
        path: st7789-chip.wasm
