name: Build Chip

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Build chip
        uses: wokwi/wokwi-chip-clang-action@main
        with:
          sources: "st7789.chip.c"
      - name: Copy st7789.chip.json
        run: sudo cp st7789.chip.json dist
      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: st7789-chip
          path: |
            dist/st7789.chip.json
            dist/st7789.chip.wasm

  # The release job only runs when you push a tag starting with "v", e.g. v1.0.0 
  release:
    name: Release
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download compiled chip
        uses: actions/download-artifact@v4
        with:
          name: st7789-chip
          path: st7789-chip
      - name: Create a zip archive
        run: cd st7789-chip && zip -9 ../st7789-chip.zip st7789-chip.*
        env:
          ZIP_VERSION: ${{ github.ref_name }}
      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          artifacts: chip.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
