name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: Setup wasm-tools  
  # You may pin to the exact commit or the version.
  # uses: jcbhmr/setup-wasm-tools@967df801cc3282b13a6a084571e0dbe429910a4c
  uses: jcbhmr/setup-wasm-tools@v2.0.2
  with:
    # Which version of wasm-tools to install. This can be an exact version specifier such as '1.0.0' or a semver range like '~1.0.0' or '1.x'. Use 'latest' to always install the latest release. Defaults to 'latest'.
    wasm-tools-version: # optional, default is latest
    # The GitHub token to use when fetching the version list from bytecodealliance/wasm-tools. You shouldn't have to touch this. The default is the 'github.token' if you're on github.com or unauthenticated (rate limited) if you're not on github.com.
    wasm-tools-token: # optional, default is ${{ github.server_url == 'https://github.com' && github.token || '' }}
          
